intralogin/config/routes.rb
Rails.application.routes.draw do
  get 'user_status/show'
  get 'user_status/update'
  resources :rooms do
    resources :messages
  end
  resources :friends
  get '/search' => 'users#search', :as => 'search_user'
  get 'users/index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: "sessions" }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session_path
  end
  resources :users
  resource :two_factor_settings, except: [:index]
  resource :otp_auth, except: [:index, :show]
  root 'users#index'

  resources :user_status, only: [:index, :show, :update]

end

intralogin/app/models/room.rb
class Room < ApplicationRecord
end

intralogin/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.fetch(:room, {})
    end
end

intralogin/app/helpers/rooms_helper.rb
module RoomsHelper
end

intralogin/app/views/rooms/_chatroom.html.erb
<script type="text/template" id="chat-room-tmpl">
<button type="button" id="close-chat-room" class="close" aria-label="Close">
      <span aria-hidden="true" class="float-right">&times;</span>
</button>
<br>
<br>
{{_.each(chats, function(chat, i) { }}
		<li class="list-group-item">
        {{ if (<%= current_user.id %> == chat.user_id) { }}
        <div class="text-right">
         {{= chat.content}}
        </div>
        {{ } else { }}
        <div class="text-left">
         {{= chat.content}}
        </div>
        {{ } }}
		</li>
{{ }) }}<br>

<form id="send-message-form">
    <input type="hidden" id="user-id" value="<%= current_user.id %>">
    <input type="text" id="content" class="form-control">
    <button type="submit" class="btn btn-primary btn-sm float-right send-message">Send</button>
</form>

</script>

<div id="chat-app">
    <div id="chat-messages-view">
</div>

intralogin/app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

intralogin/app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

intralogin/app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

intralogin/app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

intralogin/app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>
<div id="room-id" data-room-id="<%= @room.try(:id) %>"></div>